/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package beer.cheese.plugin

import org.gradle.api.Project
import org.gradle.api.Plugin

import javax.swing.Action

/**
 * A simple 'hello world' plugin.
 */
class CheeseBootPlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'beer.cheese.greeting'")
            }
        }
        project.tasks.register("cheese"){
            doLast {
                println("cheese forever")
            }
        }

        project.getDependencies().create("junit:junit:4.10");
    }
}
